import type { OrganizationProfile, HierarchyLevelNaming, HierarchyNode, OrgRole, PermissionItem } from '../types/organization'

export const defaultPermissionsList: Omit<PermissionItem, 'enabled'>[] = [
  {
    id: 'admin:global_settings',
    category: 'structure',
    label: 'Global Settings',
    description: 'Full unrestricted access to all organizational settings and system telemetry.',
  },
  {
    id: 'admin:hardware_config',
    category: 'hardware',
    label: 'Hardware Config',
    description: 'Can register, sync, and calibrate kiosk scanners and entrance turnstiles.',
  },
  {
    id: 'attendance:audit_view',
    category: 'reports',
    label: 'View Attendance Audit',
    description: 'Allows viewing and exporting of timesheets for assigned department groups.',
  },
  {
    id: 'attendance:timesheet_approve',
    category: 'tasks',
    label: 'Approve Timesheets',
    description: 'Can sign off on employee timesheets and verify logged hours.',
  },
  {
    id: 'attendance:biometric_override',
    category: 'hardware',
    label: 'Biometric Override Authorization',
    description: 'Permits manual clock-in/out logging when hardware terminal fails.',
  },
  {
    id: 'schedule:management',
    category: 'tasks',
    label: 'Schedule Management',
    description: 'Create, edit, and assign shift patterns to subordinate users.',
  },
  {
    id: 'records:view_own',
    category: 'reports',
    label: 'View Own Records',
    description: 'Standard user access. Can view personal attendance records and submit requests.',
  },
]

export const defaultLevelNamings: HierarchyLevelNaming[] = [
  { level: 1, singular: 'Primary Department', plural: 'Primary Departments' },
  { level: 2, singular: 'Sub-Department', plural: 'Sub-Departments' },
  { level: 3, singular: 'Division / Unit', plural: 'Divisions / Units' },
  { level: 4, singular: 'Specialized Lab / Desk', plural: 'Specialized Labs / Desks' },
]

export const initialHierarchyTree: HierarchyNode = {
  id: 'node-root',
  name: 'Office of the Vice Chancellor / CEO',
  code: 'OVC',
  level: 1,
  leadName: 'Prof. Faruk Adamu Kuta',
  leadRoleTitle: 'Vice Chancellor & Executive Lead',
  leadEmail: 'vc@org.edu',
  staffCount: 12,
  location: 'Senate Building, Top Floor',
  description: 'Apex administrative leadership and strategic governance.',
  children: [
    {
      id: 'node-reg',
      name: 'Registry & Institutional Secretariat',
      code: 'REG',
      level: 2,
      leadName: 'Mr. Amos Nmadu',
      leadRoleTitle: 'Registrar',
      leadEmail: 'registrar@org.edu',
      staffCount: 38,
      location: 'Senate Wing A',
      description: 'Records, council affairs, and workforce administration.',
      children: [
        {
          id: 'node-hr',
          name: 'Human Resources & Workforce Records',
          code: 'HRW',
          level: 3,
          leadName: 'Mrs. Cynthia Adeleke',
          leadRoleTitle: 'Deputy Registrar (HR)',
          staffCount: 16,
          location: 'Senate Wing A, Room 204',
          children: [
            {
              id: 'node-payroll',
              name: 'Payroll Liaison & Biometrics Desk',
              code: 'PLB',
              level: 4,
              leadName: 'Mr. David Olatunji',
              leadRoleTitle: 'Desk Officer',
              staffCount: 6,
              location: 'Room 204B',
              children: [],
            },
          ],
        },
        {
          id: 'node-sec',
          name: 'Campus Physical Security & Safety',
          code: 'SEC',
          level: 3,
          leadName: 'Captain Samuel Obi',
          leadRoleTitle: 'Chief Security Officer',
          staffCount: 22,
          location: 'Main Security Gate & Command Center',
          children: [],
        },
      ],
    },
    {
      id: 'node-bur',
      name: 'Bursary & Financial Operations',
      code: 'BUR',
      level: 2,
      leadName: 'Hadiza Mohammed',
      leadRoleTitle: 'Bursar',
      leadEmail: 'bursar@org.edu',
      staffCount: 26,
      location: 'Senate Wing B',
      description: 'Budgeting, treasury, and internal audits.',
      children: [
        {
          id: 'node-audit',
          name: 'Internal Audit & Compliance',
          code: 'IAC',
          level: 3,
          leadName: 'Dr. Joseph Ezenwa',
          leadRoleTitle: 'Director of Audit',
          staffCount: 10,
          location: 'Senate Wing B, Floor 2',
          children: [],
        },
      ],
    },
    {
      id: 'node-qa',
      name: 'Directorate of Quality Assurance',
      code: 'DQA',
      level: 2,
      leadName: 'Prof. Grace Anozie',
      leadRoleTitle: 'Director of QA',
      leadEmail: 'qa@org.edu',
      staffCount: 14,
      location: 'Academic Complex Block C',
      description: 'Standards enforcement, accreditation, and teaching inspection.',
      children: [],
    },
    {
      id: 'node-fcit',
      name: 'Faculty of Computing & IT',
      code: 'FCIT',
      level: 2,
      leadName: 'Prof. Evelyn Wright',
      leadRoleTitle: 'Dean of Faculty',
      leadEmail: 'e.wright@org.edu',
      staffCount: 64,
      location: 'Tech Complex Block A',
      description: 'Undergraduate and postgraduate computing research departments.',
      children: [
        {
          id: 'node-swe',
          name: 'Department of Software Engineering',
          code: 'SWE',
          level: 3,
          leadName: 'Dr. Alistair Vance',
          leadRoleTitle: 'Head of Department (HOD)',
          staffCount: 28,
          location: 'Block A, Level 3',
          children: [
            {
              id: 'node-cloudlab',
              name: 'Cloud & Distributed Systems Research Lab',
              code: 'CDSL',
              level: 4,
              leadName: 'Dr. Kemi Balogun',
              leadRoleTitle: 'Lab Director',
              staffCount: 8,
              location: 'Lab 305',
              children: [],
            },
          ],
        },
        {
          id: 'node-csc',
          name: 'Department of Computer Science',
          code: 'CSC',
          level: 3,
          leadName: 'Dr. Tariq Bello',
          leadRoleTitle: 'Head of Department (HOD)',
          staffCount: 28,
          location: 'Block A, Level 2',
          children: [],
        },
      ],
    },
  ],
}

export const initialRoles: OrgRole[] = [
  {
    id: 'role-admin',
    name: 'System Administrator',
    description: 'Full unrestricted access to all organizational settings, biometric enrollments, and global audit logs.',
    isSystemDefault: true,
    assignedCount: 2,
    permissions: defaultPermissionsList.map((p) => ({
      ...p,
      enabled: ['admin:global_settings', 'admin:hardware_config', 'attendance:audit_view', 'attendance:timesheet_approve', 'attendance:biometric_override', 'schedule:management', 'records:view_own'].includes(p.id),
    })),
  },
  {
    id: 'role-hod',
    name: 'Department Head / HOD',
    description: 'Manage staff attendance, approve overrides, and view localized department reporting.',
    isSystemDefault: false,
    assignedCount: 12,
    permissions: defaultPermissionsList.map((p) => ({
      ...p,
      enabled: ['attendance:audit_view', 'attendance:timesheet_approve', 'schedule:management'].includes(p.id),
    })),
  },
  {
    id: 'role-staff',
    name: 'Staff Officer',
    description: 'Standard user access. Can view personal attendance records and submit requests.',
    isSystemDefault: true,
    assignedCount: 145,
    permissions: defaultPermissionsList.map((p) => ({
      ...p,
      enabled: ['records:view_own'].includes(p.id),
    })),
  },
  {
    id: 'role-auditor',
    name: 'Auditor & Compliance Officer',
    description: 'Verifies biometric logs and time records across departments for institutional governance.',
    isSystemDefault: false,
    assignedCount: 4,
    permissions: defaultPermissionsList.map((p) => ({
      ...p,
      enabled: ['attendance:audit_view', 'records:view_own'].includes(p.id),
    })),
  },
]

export const defaultOrgProfile: OrganizationProfile = {
  id: 'org-main',
  name: 'Federal University of Technology, Minna',
  shortName: 'FUT Minna',
  slug: 'futminna-tech',
  category: 'Higher Education & Technology Research',
  deploymentLocation: 'Main Campus, Tech Park & Hybrid Stations',
  topLeaderTitle: 'Vice Chancellor & Executive Lead',
  topLeaderName: 'Prof. Faruk Adamu Kuta',
  levelNamings: defaultLevelNamings,
  hierarchyRoot: initialHierarchyTree,
  roles: initialRoles,
}
